package com.android.wazzabysama.domain.usecase.privatemessage

import com.android.wazzabysama.domain.repository.PrivateMessageRepository

class GetSearchedPrivateMessageUseCase(private val privateMessageRepository: PrivateMessageRepository)