package com.android.wazzabysama.domain.usecase.privatemessage

import com.android.wazzabysama.domain.repository.PrivateMessageRepository

class GetSavedPrivateMessageUseCase(private val privateMessageRepository: PrivateMessageRepository)