package com.android.wazzabysama.domain.usecase.privatemessage

import com.android.wazzabysama.domain.repository.PrivateMessageRepository

class UpdateSavedPrivateMessageUseCase(private val privateMessageRepository: PrivateMessageRepository)