package com.android.wazzabysama.domain.usecase

import com.android.wazzabysama.domain.repository.CategoryProblematicRepository

class DeleteSavedCategoryProblematicUseCase(private val categoryProblematicRepository: CategoryProblematicRepository)