package com.android.wazzabysama.domain.usecase

import com.android.wazzabysama.domain.repository.PrivateMessageRepository

class DeleteSavedPrivateMessageUseCase(private val privateMessageRepository: PrivateMessageRepository)