package com.android.wazzabysama.domain.usecase

import com.android.wazzabysama.domain.repository.CategoryProblematicRepository

class GetSearchCategoryProblematic(private val categoryProblematicRepository: CategoryProblematicRepository)