package com.android.wazzabysama.domain.usecase

import com.android.wazzabysama.domain.repository.CategoryProblematicRepository

class GetSearchedCategoryProblematic(private val categoryProblematicRepository: CategoryProblematicRepository)