package com.android.wazzabysama.domain.usecase

import com.android.wazzabysama.domain.repository.CategoryProblematicRepository

class SaveCategoryProblematicUseCase(private val categoryProblematicRepository: CategoryProblematicRepository)