package com.android.wazzabysama.domain.usecase.publicmessage

import com.android.wazzabysama.domain.repository.PublicMessageRepository

class DeleteSavedPublicMessageUseCase(private val publicMessageRepository: PublicMessageRepository)