package com.android.wazzabysama.domain.usecase.publicmessage

import com.android.wazzabysama.domain.repository.PublicMessageRepository

class GetSavedPublicMessageUseCase(private val publicMessageRepository: PublicMessageRepository)