package com.android.wazzabysama.domain.usecase.publicmessage

import com.android.wazzabysama.domain.repository.PublicMessageRepository

class UpdateSavedPublicMessageUseCase(private val publicMessageRepository: PublicMessageRepository)