package com.android.wazzabysama.domain.usecase.notification

import com.android.wazzabysama.domain.repository.NotificationRepository

class DeleteSavedNotificationUseCase(private val notificationRepository: NotificationRepository)