package com.android.wazzabysama.domain.usecase.notification

import com.android.wazzabysama.domain.repository.NotificationRepository

class UpdateSavedNotificationUseCase(private val notificationRepository: NotificationRepository)